<!-- AUTO-GENERATED BY CONTINUITY - DO NOT EDIT BELOW THIS LINE -->

# Project Memory (Auto-generated by Continuity)

This file contains project context and decisions. AI assistants should read this file for context. MCP tools are an optional enhancement for richer interaction when connected.

## Project Context
- **Total Decisions:** 35
- **Known Topics:** xiaozhi, context-recall, memory, decision, deploy, api, python, edge, sqlite, architecture, single-device, llm, raspberrypi, deepseek, asr

## Current State
**Repository:** xiaozhi-esp32-server
**Project Type:** Software Project
**Branch:** main

**Recent Commits:**
- `54ad9d2 chore(continuity): 同步（公开仓库脱敏核查 d184e62 决策落盘）`
- `d184e62 chore(security): 公开仓库脱敏——移除 HA 运行态（.storage 含 refresh token/jwt_key/密码哈希）与 HA 日志/DB/secrets、nohup 日志（本机文件保留，.gitignore 补齐）`
- `8e194c7 chore(continuity): 同步（CUDA/Pi 依赖核查 923c6e5 决策落盘）`
- `923c6e5 docs(deploy): Pi 安装手册增加 CPU 版 torch 步骤（默认 PyPI 轮子会静默拉入 ~2.5GB CUDA 组件且 Pi 不可用）；requirements 增加同样提示`
- `4997c1c chore(continuity): 同步（Pi 依赖核查 + sherpa 钉修复 fda9507 决策落盘）`

**Working Tree:**
- M .codex/vexp-hint.sh
- M .continuity/SESSION_NOTES.md
- M .continuity/decisions.json
- M .continuity/decisions.jsonl
- M .cursorrules
- M .github/copilot-instructions.md
- M .vexp/manifest.json
- M AGENTS.md
- M CLAUDE.md
- M GEMINI.md

## Session Context
**Goals:**
- **完成**：方案设计闭环（单例模式 / Pi5 / 全云模型 / CR 记忆集成全部定案）；代码与工具提交（6b53c22、b5c01dc、b590d32、d790d68、dbb4d48、c921504、58f9705、70cbd5e）；方案落盘 `docs/singleton-mode-plan.md`；决策全部入 Continuity；工作区干净。
- **下一步（明日）**：W1 = Phase 0 联调（CR 一次性测试实例 + 伪造快照全链路：导入/命中/幂等/隔离/降级）；可并行 W3（organizer 移植）。
- **阻塞/排除**：Pi 部署（等硬件，已排除）；组织联调需智谱 LLM key（免费款，可先注册）。
- **工期口径**：软件侧剩余 3–5 个工作日（AI 加速），约 1 周内闭环。
- **2026-09-21 里程碑**：树莓派 5 安装成功（xiaozhi-server 已就位）——待运行验收（run-acceptance 3/3 + 三项判据）与设备端联调；依赖体检项=torch 应为 CPU 轮子（如 2.14.0+cpu）、不得出现 nvidia 目录（CUDA 陷阱）、sherpa_onnx 应为 1.12.40。

**Blockers:**
- 完整模式部署前置（如采用）：本机 Java/Maven 未装、当前用户不在 docker 组、8000 端口被 pyserver 占用


## Operating Contract
1. **Load context, then search before you change.** MCP-capable agents: call `get_quick_context` at session start, then `search_decisions` before proposing changes. Shell/CLI-only agents (e.g. Copilot): run `continuity context`, then `continuity search "<topic>"` (`grep -i "<topic>" .continuity/decisions.jsonl` if the CLI is unavailable). Name any conflict with a prior decision and let the user choose. **When a prior decision informs your answer, cite it inline — "per decision-abc123, we chose X because Y" — so the user can see the memory being used, not just trust that it was.** `search_decisions` returns a `sourceTag` per result; use it.
2. **Log every deliberate change, immediately.** After each change — not batched — `continuity log "question" "answer" --tags ...`. The trigger is the change, not the commit; include the commit hash in both fields when one exists. Don't ask permission; installing Continuity is the opt-in. Tell the user you logged it.
3. **Track session state.** Edit `.continuity/SESSION_NOTES.md` for goals/blockers and an end-of-session summary.
4. **Recover & be transparent.** If you notice unlogged earlier changes, pause, log them retroactively, and say so.

## Logging paths
- MCP connected: `log_decision` / `search_decisions` / `get_quick_context` / `update_session_notes` — prefer these; they exercise the production path.
- MCP down: `continuity log "question" "answer" --tags a,b` — the always-works fallback.
- Forward work → `continuity task ...` (new ticket); in-flight note → `continuity note ...` (comment on current ticket). Don't cross-pollute.

---

## Project Instructions

# Project Instructions

Describe how this repository prefers to work with AI assistants.


---

## Recent Decisions
1. **decision-2fbfb93e** (9/21/2026) [acceptance, deploy]
   - Q: 树莓派 5 安装成功（里程碑 2026-09-21）——状态与后续验收清单？
   - A: 用户报告 xiaozhi-server 已在 Pi 5 安装成功。SESSION_NOTES 已更新：Pi 从'待硬件'转为'已安装，待验收'。验收清单：① run-acceptance.sh 期望 3/3（compileall / provider 60/60 / 冒烟 7/7）；② 三项启动判据（systemd is-active；端口 8000/8003/8765；日志无 Traceback）；③ 依赖体检（torch 应为 CPU 轮子如 2.14.0+cpu、不应出现 nvidia 目录、sherpa_onnx==1.12.40）；④ 设备端 ≥3 轮对话→断开重连→召回验证；⑤ 组织质量观察需智谱 LLM key。本轮修复链（fda9507 sherpa 钉 / 923c6e5 CPU torch 指引）是否已被 Pi 安装路径采用待确认。

2. **decision-d015004e** (9/21/2026) [api, auth]
   - Q: 公开仓库有无真实密钥被推送？（我的 4 个提交 vs 历史遗留）（d184e62）
   - A: ①本次 4 个提交（fda9507/4997c1c/923c6e5/8e194c7）逐 diff 扫描 0 命中：仅 requirements.txt、docs/singleton-mode-deploy.md、.continuity/* 与 continuity 生成的 .cursorrules/CLAUDE.md/GEMINI.md；真实运行配置 data/.config.yaml 从未入库（.gitignore:148）。②体检发现历史遗留泄漏（非本次，来自 2025-09-06 的 6cc3874）：homeassistant_config/.storage/auth 含 HA 用户 xuqianjin 的 2 个 refresh token+jwt_key（4×128 字符）与 last_used_ip，auth_provider.homeassistant 含 bcrypt 密码哈希；仓库 visibility=public → 已于 d184e62 从跟踪移除 .storage/、home-assistant.log.1、home-assistant_v2.db、secrets.yaml、main/{manager-api,manager-web}/nohup.out，并补 .gitignore（本机文件保留）。③需用户手工处置：HA 中删除这两个刷新令牌（或改...

3. **decision-a14aea6a** (9/21/2026) [cuda, deploy]
   - Q: Pi 部署需要安装 CUDA 吗？默认 pip 安装会发生什么？（923c6e5）
   - A: ①功能上完全不需要：Pi 无 NVIDIA GPU，全链路推理在云端（云端 ASR/LLM + EdgeTTS），VAD 仅 CPU 小张量；CUDA 在 Pi 上装不了也用不上。②但默认安装有坑（新发现）：torch 2.14 起 Linux 轮子（含 aarch64）在元数据里声明 CUDA 依赖（cuda-toolkit[cublas..]==13.0.3、cuda-bindings、nvidia-cudnn-cu13、nccl、nvshmem、cusparselt、triton；marker 仅 platform_system=='Linux'、不限架构）→ 在 Pi 上直接 pip install torch 会静默拉入整条 CUDA 栈：已核 aarch64 轮子合计约 2.5GB（cublas 518MB、cudnn 621MB、cusolver 213MB、cufft 204MB、nccl 206MB、cusparselt 211MB、triton 216MB、cusparse 155MB、curand 59MB、nvrtc 41MB 等），装后更大且无任何用途。③对策（已落文档 923c6e5）：Pi/无卡机先装 CPU 轮子 pip install torch torchaudio --index-url https://download.pytorch....

4. **decision-f56f13ab** (9/21/2026) [deploy, deps]
   - Q: Pi 部署依赖核查：onnxruntime 是否需要手动安装？（fda9507）
   - A: ①不需要手动装：requirements.txt 未显式列出，但 silero_vad==5.1.2 为无条件硬依赖（onnxruntime>=1.16.1），markitdown→magika（Py≥3.10）也要求 → pip install -r requirements.txt 必带；aarch64 轮子覆盖 cp310–cp314（onnxruntime 1.23.2，cp311 约 14.5MB），pip 直装无需 apt/编译。②运行时并不使用：VAD=silero.py 走 torch.hub 本地仓 models/snakers4_silero-vad（.jit 路径，utils_vad.py 仅函数内延迟 import）；ASR=云端流式 → 保留勿删。③硬约束（实测 torch 2.14 源码）：torch.hub.load 校验 hubconf dependencies=['torch','torchaudio']，缺 torchaudio 直接 RuntimeError → torch/torchaudio 均为 SileroVAD 运行时必需；deploy 手册原裁剪建议已更正。④顺带发现并修复部署阻塞：sherpa_onnx==1.12.4 不存在于 PyPI（29 个精确钉中唯一不可解析）→ 改 1.12.40（同线最近；aarch64 cp3...

5. **decision-adc11d03** (9/21/2026) [deploy, docs]
   - Q: 单例模式启动手册落盘并推送 GitHub（5bd83e4）
   - A: ①新增 docs/singleton-mode-start.md：启动前检查（venv/.config.yaml/IP/端口空闲）→ 启动顺序（CR 先、xiaozhi 后；CR 缺席时 xiaozhi 走空记忆降级不阻塞）→ 启停/日志速查表 → 三项成功判据（is-active/端口 8000·8003·8765/日志无 Traceback）→ 设备端联调（≥3 轮触发组织、save 日志 nodes/edges、raw turns 在 data/context_recall）→ 日常运维（linger 核对、备份两处数据目录）→ 验收复跑（3 项）→ 启动故障速查表（端口占用/配置错/找不到 app.py/召回空/时钟 InvalidTimeStamp/ffprobe/代理）→ 开发机差异附录。②docs/singleton-mode-deploy.md header 增加交叉引用（deploy 负责装、start 负责起）。③事实复核：install-singleton-service.sh 仅 enable 不 start（首次须手动）；CR 的 install-user-service.sh 为 enable --now；端口 8000/8003/8765；min_user_turns=3。④推送 origin/main 9fe98d1..5bd83e4；未夹带 ...

---

*Auto-generated by Continuity | Updated: 2026-09-21*

<!-- END CONTINUITY AUTO-GENERATED CONTENT -->
