<!-- AUTO-GENERATED BY CONTINUITY - DO NOT EDIT BELOW THIS LINE -->

# Project Memory (Auto-generated by Continuity)

This file contains project context and decisions. AI assistants should read this file for context. MCP tools are an optional enhancement for richer interaction when connected.

## Project Context
- **Total Decisions:** 23
- **Known Topics:** xiaozhi, context-recall, decision, api, python, edge, memory, sqlite, architecture, single-device, llm, raspberrypi, asr, deploy, deepseek

## Current State
**Repository:** xiaozhi-esp32-server
**Project Type:** Software Project
**Branch:** main
**Tracking:** ahead 18, behind 0

**Recent Commits:**
- `4c12fc1 docs(deploy): 单例模板补充 DeepSeek/Kimi LLM 选项`
- `ea36e78 feat(deploy): 单例部署产物（配置模板/systemd 安装/验收脚本/部署手册）`
- `7fd736e chore(continuity): 同步自动生成文件与会话笔记（W2 收尾）`
- `cb89a3f chore(continuity): W2 验收记录（ee6bfad）`
- `ee6bfad feat(memory): context_recall 记忆 provider（客户端/组织器/快照/存储 + 自跑测试）`

**Working Tree:**
- M .continuity/SESSION_NOTES.md
- M .continuity/decisions.json
- M .continuity/decisions.jsonl
- M .cursorrules
- M CLAUDE.md
- M GEMINI.md

## Session Context
**Goals:**
- **完成**：方案设计闭环（单例模式 / Pi5 / 全云模型 / CR 记忆集成全部定案）；代码与工具提交（6b53c22、b5c01dc、b590d32、d790d68、dbb4d48、c921504、58f9705、70cbd5e）；方案落盘 `docs/singleton-mode-plan.md`；决策全部入 Continuity；工作区干净。
- **下一步（明日）**：W1 = Phase 0 联调（CR 一次性测试实例 + 伪造快照全链路：导入/命中/幂等/隔离/降级）；可并行 W3（organizer 移植）。
- **阻塞/排除**：Pi 部署（等硬件，已排除）；组织联调需智谱 LLM key（免费款，可先注册）。

**Blockers:**
- 完整模式部署前置（如采用）：本机 Java/Maven 未装、当前用户不在 docker 组、8000 端口被 pyserver 占用

## Operating Contract
1. **Load context, then search before you change.** MCP-capable agents: call `get_quick_context` at session start, then `search_decisions` before proposing changes. Shell/CLI-only agents (e.g. Copilot): run `continuity context`, then `continuity search "<topic>"` (`grep -i "<topic>" .continuity/decisions.jsonl` if the CLI is unavailable). Name any conflict with a prior decision and let the user choose. **When a prior decision informs your answer, cite it inline — "per decision-abc123, we chose X because Y" — so the user can see the memory being used, not just trust that it was.** `search_decisions` returns a `sourceTag` per result; use it.
2. **Log every deliberate change, immediately.** After each change — not batched — `continuity log "question" "answer" --tags ...`. The trigger is the change, not the commit; include the commit hash in both fields when one exists. Don't ask permission; installing Continuity is the opt-in. Tell the user you logged it.
3. **Track session state.** Edit `.continuity/SESSION_NOTES.md` for goals/blockers and an end-of-session summary.
4. **Recover & be transparent.** If you notice unlogged earlier changes, pause, log them retroactively, and say so.

## Logging paths
- MCP connected: `log_decision` / `search_decisions` / `get_quick_context` / `update_session_notes` — prefer these; they exercise the production path.
- MCP down: `continuity log "question" "answer" --tags a,b` — the always-works fallback.
- Forward work → `continuity task ...` (new ticket); in-flight note → `continuity note ...` (comment on current ticket). Don't cross-pollute.

---

## Project Instructions

# Project Instructions

Describe how this repository prefers to work with AI assistants.


---

## Recent Decisions
1. **decision-49832443** (9/21/2026) [context-recall, knowledge-service]
   - Q: CR 侧根治待办已入库 knowledge-agent-service（13edc33）
   - A: docs/cjk-recall-todo.md：①CJK 词法 OR 回退（bigram/trigram，对齐 ASCII 的 AND+OR 并联）；②空 workspace 严格 scope 开关；③memory 单元向量通道（/v1/embed 或导入时生成）；④跨会话近义节点去重（LLM 措辞不同→节点累积）。以上均为知识服务仓库后续迭代项，不影响 xiaozhi 当前链路。

2. **decision-0db75b68** (9/21/2026) [context-recall, deepseek]
   - Q: query_utils 拆词多路检索落地（359fae4）：CR CJK 连续子串 AND 的 provider 侧规避
   - A: ①真机发现：CR 词法门对 CJK 是"连续子串 AND"（memory_store.cjk_phrase：每个连续片段必须逐字出现），整句提问必漏；语义通道需调用方随请求带 embedding（xiaozhi 无嵌入器→不参与）。②实现：query_utils.build_query_candidates（停用词剔除+多字片段优先+单字仅兜底）+ merge_hit_lists（按路序合并去重）；query_memory 改多路并行检索（asyncio.gather）。③单字兜底原因：实测候选"光"会把 ws='' 的 continuity 历史决策拉进客厅灯检索（_match 显式包含 ws='' 单元）。④验证：自测 74/74（新增 11.1-11.9 拆词、12.1-12.4 多路合并）；真机三条整句问句（儿子/灯光/作息）全部命中且无跨 scope 噪声；live 联调脚本入库 test/test_context_recall_live.py。⑤提交 359fae4（5 文件 +370）；方案文档 §9 已记。

3. **decision-92bdc575** (9/21/2026) [aliyun, asr]
   - Q: 联调配置就绪：data/.config.yaml 切换为 DeepSeek + 阿里云流式（用户选型）
   - A: ①用户选型：LLM=DeepSeek（deepseek-chat）；ASR=阿里云流式（AliyunStreamASR）。②操作：原 data/.config.yaml（manager 失效配置）备份为 data/.config.yaml.bak-20260921；单例模板覆盖并预配置，用户只需填 4 个占位符（L51 deepseek api_key；L64-66 aliyun appkey/access_key_id/access_key_secret）。③代码确认：阿里云 provider 支持 access_key_id+secret 自动换 token（create_token→_refresh_token），无需手填 24h token。④密钥纪律：用户自行填入，不经聊天传输；data/ 已被 gitignore（.gitignore:148）防误提交；后续验证不读取密钥行。⑤CR 可达性：本地 8765 未起（联调时启动），8876 测试实例在跑。⑥入仓模板 config_singleton.yaml 保持四选一注释形态未动。

4. **decision-75c8cc9f** (9/21/2026) [api, deepseek]
   - Q: 单例模板补充 DeepSeek/Kimi LLM 选项（4c12fc1）：LLM 四选一
   - A: ①DeepSeekLLM：内置块（type openai/model deepseek-chat/url api.deepseek.com 均为默认值），自定义侧只需填 api_key（深合并覆盖）。②KimiLLM：默认配置无此键，自定义块必须写全四项（type openai、model_name moonshot-v1-8k（以控制台为准）、url https://api.moonshot.cn/v1、api_key）。③OpenAI 兼容 provider 同时接受 base_url（优先）与 url 字段——已读 openai.py 确认。④成本：智谱 glm-4-flash 免费款 vs DeepSeek/Kimi 按量付费。⑤记忆组织器复用所选 LLM（CR 服务自身不调模型），换 DeepSeek/Kimi 同时提升组织质量。⑥部署手册同步（前置清单+第2步）。

5. **decision-92904900** (9/21/2026) [deploy, python]
   - Q: 单例部署产物落盘（ea36e78）：配置模板/服务安装/验收脚本/部署手册
   - A: ①config_singleton.yaml：data/.config.yaml 覆盖式模板（merge_configs 深合并、custom 优先）；含 server/selected_module（DoubaoStreamASR 或 AliyunStreamASR 二选一、ChatGLMLLM 默认）/LLM+ASR 密钥占位/Memory.context_recall 完整块（scope_fallback='none' 硬约束）。②scripts/install-singleton-service.sh：自定位、校验 .venv，生成 ~/.config/systemd/user/xiaozhi-server.service（WorkingDirectory=server_dir、ExecStart=.venv/bin/python app.py、Restart=on-failure/10s、network-online、WantedBy=default.target），enable+linger 但不自动 start；无 manager 依赖。③scripts/run-acceptance.sh：3 项聚合（compileall / provider 60/60 / 冒烟 7/7；CR_SMOKE_URL 覆盖默认 127.0.0.1:8765）。④docs/sing...

---

*Auto-generated by Continuity | Updated: 2026-09-21*

<!-- END CONTINUITY AUTO-GENERATED CONTENT -->
